import { useEffect, useState } from "react";
import { ArrowRight, CircleAlert, CircleCheck, Clock3 } from "lucide-react";
import { api } from "../../lib/api";
import type { Account, AuditEvent } from "../../lib/types";
import { formatDate } from "../accounts/account-format";

export function OverviewPage({ onNavigate }: { onNavigate: (path: string) => void }) {
  const [accounts, setAccounts] = useState<Account[]>([]); const [audits, setAudits] = useState<AuditEvent[]>([]);
  useEffect(() => { Promise.all([api.get<Account[]>("/api/codex/accounts"), api.get<AuditEvent[]>("/api/codex/audit").catch(() => [])]).then(([nextAccounts, nextAudits]) => { setAccounts(nextAccounts); setAudits(nextAudits); }); }, []);
  return <section className="page overview-page"><header className="page-header"><div><h1>运行概览</h1><p>快速了解账号健康、额度与近期操作。</p></div><button className="button primary" onClick={() => onNavigate("/accounts")}>查看全部账号<ArrowRight size={15} /></button></header><div className="overview-strip"><Metric icon={CircleCheck} label="可用账号" value={accounts.filter((item) => item.status === "ready").length} tone="success" /><Metric icon={CircleAlert} label="需要处理" value={accounts.filter((item) => item.status !== "ready").length} tone="warning" /><Metric icon={Clock3} label="最近额度采集" value={formatDate(accounts.map((item) => item.usage?.collectedAt).filter(Boolean).sort().at(-1))} /></div><div className="overview-columns"><section><header><h2>账号状态</h2><button onClick={() => onNavigate("/accounts")}>全部账号</button></header>{accounts.slice(0, 5).map((account) => <div className="overview-row" key={account.id}><span className="account-avatar">{account.email[0].toUpperCase()}</span><span><strong>{account.email}</strong><small>{account.alias || "未设置别名"}</small></span><span className={`status-text ${account.status === "ready" ? "success" : "warning"}`}><i />{account.status === "ready" ? "正常" : "待处理"}</span></div>)}</section><section><header><h2>最近操作</h2><button onClick={() => onNavigate("/audit")}>查看审计</button></header>{audits.slice(0, 5).map((event) => <div className="overview-row audit" key={event.id}><span><strong>{event.action}</strong><small>{event.actorId} · {formatDate(event.createdAt)}</small></span><span>{event.result === "success" ? "成功" : "失败"}</span></div>)}</section></div></section>;
}
function Metric({ icon: Icon, label, value, tone = "" }: { icon: typeof CircleCheck; label: string; value: string | number; tone?: string }) { return <div className="overview-metric"><Icon className={tone} size={20} /><span><small>{label}</small><strong className={tone}>{value}</strong></span></div>; }
